version: "2.3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: ting-dp
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/html
      - ./developer/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ting
networks:
  ting:
    external: true

